"""
Audio processing module for Chatterbox TTS.

This module provides functionality for post-processing audio generated by the Chatterbox TTS engine.
"""

import os
import logging
from typing import Dict, Optional, Tuple, Union, List

import torch
import torchaudio
import torchaudio.functional as F
import torchaudio.transforms as T
from pydub import AudioSegment
import ffmpeg

logger = logging.getLogger(__name__)


class AudioProcessor:
    """
    Provides audio post-processing functionality for TTS-generated audio.
    """

    def __init__(self, sample_rate: int = 24000):
        """
        Initialize the audio processor.

        Args:
            sample_rate: The sample rate of the audio to process.
        """
        self.sample_rate = sample_rate

    def normalize_volume(
        self, 
        audio: Union[torch.Tensor, str], 
        target_db: float = -16.0
    ) -> torch.Tensor:
        """
        Normalize the volume of an audio file or tensor.

        Args:
            audio: The audio to normalize, either as a tensor or a path to an audio file.
            target_db: The target dB level for normalization.

        Returns:
            The normalized audio as a tensor.
        """
        # Load audio if a path is provided
        if isinstance(audio, str):
            waveform, sample_rate = torchaudio.load(audio)
            if sample_rate != self.sample_rate:
                waveform = self._resample(waveform, sample_rate, self.sample_rate)
        else:
            waveform = audio

        # Calculate current RMS
        rms = torch.sqrt(torch.mean(waveform ** 2))
        current_db = 20 * torch.log10(rms + 1e-10)
        
        # Calculate gain needed to reach target dB
        gain = 10 ** ((target_db - current_db) / 20)
        
        # Apply gain
        normalized = waveform * gain
        
        logger.info(f"Normalized audio from {current_db:.2f}dB to {target_db:.2f}dB")
        return normalized

    def add_pause(
        self, 
        audio: torch.Tensor, 
        duration_ms: int = 500
    ) -> torch.Tensor:
        """
        Add a pause (silence) to the end of an audio tensor.

        Args:
            audio: The audio tensor to add a pause to.
            duration_ms: The duration of the pause in milliseconds.

        Returns:
            The audio tensor with the pause added.
        """
        # Calculate number of samples for the pause
        num_samples = int(self.sample_rate * duration_ms / 1000)
        
        # Create silence tensor
        silence = torch.zeros((audio.shape[0], num_samples), dtype=audio.dtype, device=audio.device)
        
        # Concatenate audio and silence
        result = torch.cat([audio, silence], dim=1)
        
        logger.info(f"Added {duration_ms}ms pause to audio")
        return result

    def reduce_noise(
        self, 
        audio: torch.Tensor, 
        reduction_amount: float = 0.1
    ) -> torch.Tensor:
        """
        Apply basic noise reduction to an audio tensor.
        
        This is a simple implementation that applies a noise gate.

        Args:
            audio: The audio tensor to reduce noise in.
            reduction_amount: The threshold for noise reduction (0.0 to 1.0).

        Returns:
            The noise-reduced audio tensor.
        """
        # Calculate threshold based on max amplitude
        max_amp = torch.max(torch.abs(audio))
        threshold = max_amp * reduction_amount
        
        # Apply noise gate
        mask = torch.abs(audio) < threshold
        denoised = audio.clone()
        denoised[mask] = 0.0
        
        logger.info(f"Applied noise reduction with threshold {threshold:.6f}")
        return denoised

    def convert_format(
        self, 
        input_path: str, 
        output_path: str, 
        format: str = 'wav', 
        bitrate: str = '192k'
    ) -> str:
        """
        Convert an audio file to a different format.

        Args:
            input_path: Path to the input audio file.
            output_path: Path to save the converted audio file.
            format: The output format (wav, mp3, flac).
            bitrate: The bitrate for compressed formats.

        Returns:
            The path to the converted audio file.
        """
        try:
            # Ensure output directory exists
            os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
            
            # Use ffmpeg for conversion
            (
                ffmpeg
                .input(input_path)
                .output(output_path, format=format, audio_bitrate=bitrate)
                .run(quiet=True, overwrite_output=True)
            )
            
            logger.info(f"Converted audio from {input_path} to {output_path} ({format} format)")
            return output_path
            
        except Exception as e:
            logger.error(f"Error converting audio format: {e}")
            raise

    def embed_metadata(
        self, 
        input_path: str, 
        output_path: str, 
        metadata: Dict[str, str]
    ) -> str:
        """
        Embed metadata into an audio file.

        Args:
            input_path: Path to the input audio file.
            output_path: Path to save the audio file with embedded metadata.
            metadata: Dictionary of metadata to embed.

        Returns:
            The path to the audio file with embedded metadata.
        """
        try:
            # Ensure output directory exists
            os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
            
            # Prepare metadata arguments for ffmpeg
            metadata_args = {}
            for key, value in metadata.items():
                metadata_args[f"metadata:g:{key}"] = value
            
            # Use ffmpeg to embed metadata
            (
                ffmpeg
                .input(input_path)
                .output(output_path, **metadata_args)
                .run(quiet=True, overwrite_output=True)
            )
            
            logger.info(f"Embedded metadata into {output_path}")
            return output_path
            
        except Exception as e:
            logger.error(f"Error embedding metadata: {e}")
            raise

    def _resample(
        self, 
        waveform: torch.Tensor, 
        orig_freq: int, 
        new_freq: int
    ) -> torch.Tensor:
        """
        Resample audio to a different sample rate.

        Args:
            waveform: The audio tensor to resample.
            orig_freq: The original sample rate.
            new_freq: The target sample rate.

        Returns:
            The resampled audio tensor.
        """
        if orig_freq == new_freq:
            return waveform
            
        resampler = T.Resample(orig_freq, new_freq)
        return resampler(waveform)